### PR TITLE
Cm12

### PR DESCRIPTION
**Pull request by AndroidAddict92**

### CODE REVIEW

**Comment by Dm47021** [comment]
My question is, Why do we need to redo this ?? it makes no sense to me.. and does it boot ? i never did get it fully booting on CM12

**Comment by AndroidAddict92** [comment]
This doesn't even build with 12 lol. I've been at it all day. That request was by total accident, meant to do something else

**Comment by Dm47021** [comment]
LOL it can happen, i had gotten cm12 to build, it gets boot animation, then LOOP

**Comment by AndroidAddict92** [comment]
I was trying to build 12.1 since a user at AF requested it.

**Comment by Dm47021** [comment]
ill try to get annother f6, my crazy ex gf trashed ALL my phones,

**Comment by AndroidAddict92** [comment]
I was going to work blindly on it. Let me know if you need anything, my nick at AF is MikeHoncho and AndroidAddict||AA at xda

**Comment by Dm47021** [comment]
well, what is it you are trying to do.. might be of some help

**Comment by AndroidAddict92** [comment]
I had started a caf kernel and was working on the device tree, I think I have taken care of most of the device tree errors for now. I am running into mainly kernel errors now

**Comment by Dm47021** [comment]
kernel needs ALOT more work, and things ported over.. kernels are kinda my area

**Comment by AndroidAddict92** [comment]
Device trees are my area (sometimes) lol. All I did to caf kernel was the basics, i'm still learning about kernels.

Device Tree: https://github.com/LEPT-Development/android_device_lge_f6mt

Kernel: https://github.com/LEPT-Development/android_kernel_lge_msm8960

If you want to talk in IRC you can join the freenode server and join channel #lept-dev

**Comment by Dm47021** [comment]
from what i see you did port over the board, configs, or drivers

**Comment by AndroidAddict92** [comment]
drivers, configs, boot, and some other lge stuff

Edit: here is my last error: http://hastebin.com/eguqudequd.dos

**Pull request closed without merging**
